import cv2
img =cv2.imread("rose.jpg")
cv2.imshow('original', img)
cv2.waitKey(0)
img_gray = cv2.cvtColor(img, cv2.cvtColor_BGR2GRAY)
img_blur = cv2.GaussianBlur(img_gray, (3,3), 0)
sobelx = cv2.Sobel(src=img, ddepth=cv2.CV_64F, dx=1, dy=0, ksize=5)
sobely = cv2.Sobel(src=img, ddepth=cv2.CV_64F, dx=0, dy=1, ksize=5)
sobelxy = cv2.Sobel(src=img, ddepth=cv2.CV_64F, dx=1, dy=1, ksize=5)
cv2.imshow('sobelx', sobelx)
cv2.waitKey(0)
cv2.imshow('sobely', sobely)
cv2.waitKey(0)
cv2.imshow('sobelxy', sobelxy)
cv2.waitKey(0)
cv2.destroyAllWindows()
